/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Permanently delete your account and data */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download all of your data */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            activeSessions: number;
                            auditLog: {
                                action: string;
                                createdAt: string;
                                entityId: string | null;
                                entityType: string | null;
                            }[];
                            exportedAt: string;
                            properties: components["schemas"]["Property"][];
                            user: {
                                createdAt: string;
                                displayName: string | null;
                                email: string;
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                role: "USER" | "ADMIN";
                            };
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            csrfToken: string;
                            expiresAt: string;
                            user: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user, or 401 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            csrfToken: string;
                            user: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and sign in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        displayName?: string;
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            csrfToken: string;
                            expiresAt: string;
                            user: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud-nowcast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cloud movement nowcast (UNAVAILABLE unless sub-hourly satellite data exists) */
        get: {
            parameters: {
                query: {
                    latitude: number;
                    longitude: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            provenance: components["schemas"]["Provenance"];
                            unit?: string;
                            value: null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find the address at a coordinate */
        get: {
            parameters: {
                query: {
                    latitude: number;
                    longitude: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            provenance: components["schemas"]["Provenance"];
                            unit?: string;
                            value: {
                                address?: {
                                    [key: string]: string;
                                };
                                boundingBox?: [
                                    number,
                                    number,
                                    number,
                                    number
                                ];
                                importance?: number;
                                kind: string;
                                label: string;
                                latitude: number;
                                longitude: number;
                                osm?: {
                                    id: number;
                                    type: string;
                                };
                            } | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search an address, locality or place name */
        get: {
            parameters: {
                query: {
                    q: string;
                    limit?: number;
                    /** @description Comma-separated ISO country codes to restrict to, for example in */
                    countries?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            provenance: components["schemas"]["Provenance"];
                            unit?: string;
                            value: {
                                address?: {
                                    [key: string]: string;
                                };
                                boundingBox?: [
                                    number,
                                    number,
                                    number,
                                    number
                                ];
                                importance?: number;
                                kind: string;
                                label: string;
                                latitude: number;
                                longitude: number;
                                osm?: {
                                    id: number;
                                    type: string;
                                };
                            }[] | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: the process is up */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            time: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Solar resource, weather and yield per kWp at a coordinate (not saved) */
        get: {
            parameters: {
                query: {
                    latitude: number;
                    longitude: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            confidence: number;
                            /** @enum {string} */
                            dataQuality: "MINIMAL" | "PARTIAL" | "FULL";
                            requested: components["schemas"]["GeoPoint"];
                            solar: {
                                annualGhiKwhM2Day: {
                                    provenance: components["schemas"]["Provenance"];
                                    unit?: string;
                                    value: number | null;
                                };
                                forecastNext24hKwhPerKwp: {
                                    provenance: components["schemas"]["Provenance"];
                                    unit?: string;
                                    value: number | null;
                                };
                                yieldKwhPerKwpDay: {
                                    provenance: components["schemas"]["Provenance"];
                                    unit?: string;
                                    value: number | null;
                                };
                            };
                            sources: {
                                at: string;
                                dataType: string;
                                note: string;
                                ok: boolean;
                                provider: string;
                                status: string;
                            }[];
                            unavailable: {
                                reason: string;
                                what: string;
                            }[];
                            warnings: string[];
                            weather: {
                                airTemperature: {
                                    provenance: components["schemas"]["Provenance"];
                                    unit?: string;
                                    value: number | null;
                                };
                                cloudCover: {
                                    provenance: components["schemas"]["Provenance"];
                                    unit?: string;
                                    value: number | null;
                                };
                                globalHorizontalIrradiance: {
                                    provenance: components["schemas"]["Provenance"];
                                    unit?: string;
                                    value: number | null;
                                };
                            };
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your saved properties */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            properties: components["schemas"]["Property"][];
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Save a property at a location */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        address?: string;
                        latitude: number;
                        longitude: number;
                        name: string;
                        positionAccuracyM?: number;
                        positionSource: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One property */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a property and its geometry */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Rename or re-address a property */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        address?: string | null;
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/properties/{id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build a new Energy Twin version from every reachable real source */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnergyTwin"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/{id}/cloud-nowcast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cloud nowcast for a property */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            provenance: components["schemas"]["Provenance"];
                            unit?: string;
                            value: null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/{id}/geometry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a roof or plot outline you drew */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description GeoJSON ring of [longitude, latitude] pairs; first point repeated as last. */
                        ring: [
                            number,
                            number
                        ][];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/{id}/twin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The latest Energy Twin */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnergyTwin"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/{id}/twin/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every Energy Twin version, newest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            versions: {
                                confidence: number;
                                createdAt: string;
                                /** @enum {string} */
                                dataQuality: "MINIMAL" | "PARTIAL" | "FULL";
                                /** Format: uuid */
                                id: string;
                                reason: string;
                                version: number;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/{id}/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weather at one of your properties */
        get: {
            parameters: {
                query?: {
                    days?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            current: {
                                [key: string]: {
                                    provenance: components["schemas"]["Provenance"];
                                    unit?: string;
                                    value: number | null;
                                };
                            };
                            elevationM: number | null;
                            fetchedAt: string;
                            grid: components["schemas"]["GeoPoint"];
                            hourly: {
                                [key: string]: {
                                    provenance: components["schemas"]["Provenance"];
                                    unit?: string;
                                    value: {
                                        time: string;
                                        value: number;
                                    }[] | null;
                                };
                            };
                            notes: string[];
                            quality: {
                                reasons: string[];
                                rejected: number;
                                variable: string;
                            }[];
                            requested: components["schemas"]["GeoPoint"];
                            /** @description True when the provider did not answer and an older copy is shown. */
                            stale: boolean;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Database and external provider health, from real recent calls */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            database: {
                                error: string | null;
                                latencyMs: number | null;
                                postgis: string | null;
                                /** @enum {string} */
                                state: "healthy" | "down";
                            };
                            generatedAt: string;
                            providers: {
                                calls: number;
                                failures: number;
                                lastError: string | null;
                                lastErrorAt: string | null;
                                lastSuccessAt: string | null;
                                p50Ms: number | null;
                                p95Ms: number | null;
                                provider: string;
                                /** @enum {string} */
                                state: "healthy" | "degraded" | "down" | "unknown";
                            }[];
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            windowMinutes: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current model analysis and hourly forecast at a coordinate */
        get: {
            parameters: {
                query: {
                    latitude: number;
                    longitude: number;
                    days?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            current: {
                                [key: string]: {
                                    provenance: components["schemas"]["Provenance"];
                                    unit?: string;
                                    value: number | null;
                                };
                            };
                            elevationM: number | null;
                            fetchedAt: string;
                            grid: components["schemas"]["GeoPoint"];
                            hourly: {
                                [key: string]: {
                                    provenance: components["schemas"]["Provenance"];
                                    unit?: string;
                                    value: {
                                        time: string;
                                        value: number;
                                    }[] | null;
                                };
                            };
                            notes: string[];
                            quality: {
                                reasons: string[];
                                rejected: number;
                                variable: string;
                            }[];
                            requested: components["schemas"]["GeoPoint"];
                            /** @description True when the provider did not answer and an older copy is shown. */
                            stale: boolean;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EnergyTwin: {
            assumptions: {
                key: string;
                rationale: string;
                unit: string;
                value: number;
            }[];
            /** @description Weighted share of the needed inputs that are available: data completeness, not a probability. */
            confidence: number;
            confidenceBasis: {
                available: boolean;
                item: string;
                weight: number;
            }[];
            confidenceMeaning: string;
            consumption: {
                estimatedDailyLoadKwh: {
                    provenance: components["schemas"]["Provenance"];
                    unit?: string;
                    value: number | null;
                };
            };
            createdAt: string;
            /** @enum {string} */
            dataQuality: "MINIMAL" | "PARTIAL" | "FULL";
            energyAutonomyScore: {
                provenance: components["schemas"]["Provenance"];
                unit?: string;
                value: number | null;
            };
            geometry: {
                kind: ("BUILDING_FOOTPRINT" | "USER_POLYGON") | null;
                roofAreaM2: {
                    provenance: components["schemas"]["Provenance"];
                    unit?: string;
                    value: number | null;
                };
            };
            /** Format: uuid */
            id: string;
            location: {
                elevationM: number | null;
                latitude: number;
                longitude: number;
            };
            /** Format: uuid */
            propertyId: string;
            reason: string;
            satellite: {
                provenance: components["schemas"]["Provenance"];
                unit?: string;
                value: components["schemas"]["SatelliteScene"] | null;
            };
            solar: {
                annualGhiKwhM2Day: {
                    provenance: components["schemas"]["Provenance"];
                    unit?: string;
                    value: number | null;
                };
                capacityKwEstimate: {
                    provenance: components["schemas"]["Provenance"];
                    unit?: string;
                    value: number | null;
                };
                clearSkyKwhM2Day: {
                    provenance: components["schemas"]["Provenance"];
                    unit?: string;
                    value: number | null;
                };
                clearnessIndex: {
                    provenance: components["schemas"]["Provenance"];
                    unit?: string;
                    value: number | null;
                };
                estimatedDailyGenerationKwh: {
                    provenance: components["schemas"]["Provenance"];
                    unit?: string;
                    value: number | null;
                };
                forecastNext24hGhiKwhM2: {
                    provenance: components["schemas"]["Provenance"];
                    unit?: string;
                    value: number | null;
                };
                forecastNext24hKwhPerKwp: {
                    provenance: components["schemas"]["Provenance"];
                    unit?: string;
                    value: number | null;
                };
                usableRoofAreaM2: {
                    provenance: components["schemas"]["Provenance"];
                    unit?: string;
                    value: number | null;
                };
                yieldKwhPerKwpDay: {
                    provenance: components["schemas"]["Provenance"];
                    unit?: string;
                    value: number | null;
                };
            };
            sources: {
                at: string;
                dataType: string;
                note: string;
                ok: boolean;
                provider: string;
                status: string;
            }[];
            tariff: {
                provenance: components["schemas"]["Provenance"];
                unit?: string;
                value: null;
            };
            unavailable: {
                reason: string;
                what: string;
            }[];
            version: number;
            warnings: string[];
        };
        EnergyTwinInput: {
            assumptions: {
                key: string;
                rationale: string;
                unit: string;
                value: number;
            }[];
            /** @description Weighted share of the needed inputs that are available: data completeness, not a probability. */
            confidence: number;
            confidenceBasis: {
                available: boolean;
                item: string;
                weight: number;
            }[];
            confidenceMeaning: string;
            consumption: {
                estimatedDailyLoadKwh: {
                    provenance: components["schemas"]["ProvenanceInput"];
                    unit?: string;
                    value: number | null;
                };
            };
            createdAt: string;
            /** @enum {string} */
            dataQuality: "MINIMAL" | "PARTIAL" | "FULL";
            energyAutonomyScore: {
                provenance: components["schemas"]["ProvenanceInput"];
                unit?: string;
                value: number | null;
            };
            geometry: {
                kind: ("BUILDING_FOOTPRINT" | "USER_POLYGON") | null;
                roofAreaM2: {
                    provenance: components["schemas"]["ProvenanceInput"];
                    unit?: string;
                    value: number | null;
                };
            };
            /** Format: uuid */
            id: string;
            location: {
                elevationM: number | null;
                latitude: number;
                longitude: number;
            };
            /** Format: uuid */
            propertyId: string;
            reason: string;
            satellite: {
                provenance: components["schemas"]["ProvenanceInput"];
                unit?: string;
                value: components["schemas"]["SatelliteSceneInput"] | null;
            };
            solar: {
                annualGhiKwhM2Day: {
                    provenance: components["schemas"]["ProvenanceInput"];
                    unit?: string;
                    value: number | null;
                };
                capacityKwEstimate: {
                    provenance: components["schemas"]["ProvenanceInput"];
                    unit?: string;
                    value: number | null;
                };
                clearSkyKwhM2Day: {
                    provenance: components["schemas"]["ProvenanceInput"];
                    unit?: string;
                    value: number | null;
                };
                clearnessIndex: {
                    provenance: components["schemas"]["ProvenanceInput"];
                    unit?: string;
                    value: number | null;
                };
                estimatedDailyGenerationKwh: {
                    provenance: components["schemas"]["ProvenanceInput"];
                    unit?: string;
                    value: number | null;
                };
                forecastNext24hGhiKwhM2: {
                    provenance: components["schemas"]["ProvenanceInput"];
                    unit?: string;
                    value: number | null;
                };
                forecastNext24hKwhPerKwp: {
                    provenance: components["schemas"]["ProvenanceInput"];
                    unit?: string;
                    value: number | null;
                };
                usableRoofAreaM2: {
                    provenance: components["schemas"]["ProvenanceInput"];
                    unit?: string;
                    value: number | null;
                };
                yieldKwhPerKwpDay: {
                    provenance: components["schemas"]["ProvenanceInput"];
                    unit?: string;
                    value: number | null;
                };
            };
            sources: {
                at: string;
                dataType: string;
                note: string;
                ok: boolean;
                provider: string;
                status: string;
            }[];
            tariff: {
                provenance: components["schemas"]["ProvenanceInput"];
                unit?: string;
                value: null;
            };
            unavailable: {
                reason: string;
                what: string;
            }[];
            version: number;
            warnings: string[];
        };
        ErrorResponse: {
            error: {
                /** @description Stable machine-readable code, for example INVALID_COORDINATES. */
                code: string;
                details?: unknown;
                /** @description Plain-language explanation for the user. */
                message: string;
                requestId?: string;
            };
        };
        ErrorResponseInput: {
            error: {
                /** @description Stable machine-readable code, for example INVALID_COORDINATES. */
                code: string;
                details?: unknown;
                /** @description Plain-language explanation for the user. */
                message: string;
                requestId?: string;
            };
        };
        GeoPoint: {
            latitude: number;
            longitude: number;
        };
        GeoPointInput: {
            latitude: number;
            longitude: number;
        };
        Property: {
            address: string | null;
            createdAt: string;
            geometry: {
                items: {
                    areaM2: number;
                    geojson: unknown;
                    /** Format: uuid */
                    id: string;
                    /** @enum {string} */
                    kind: "BUILDING_FOOTPRINT" | "USER_POLYGON";
                    source: string;
                }[];
                message: string | null;
                /** @enum {string} */
                status: "AVAILABLE" | "UNAVAILABLE";
            };
            /** Format: uuid */
            id: string;
            latitude: number;
            longitude: number;
            name: string;
            position: {
                accuracyM: number | null;
                description: string;
                label: string;
                note: string;
                source: string;
            };
            updatedAt: string;
            warnings: string[];
        };
        PropertyInput: {
            address: string | null;
            createdAt: string;
            geometry: {
                items: {
                    areaM2: number;
                    geojson: unknown;
                    /** Format: uuid */
                    id: string;
                    /** @enum {string} */
                    kind: "BUILDING_FOOTPRINT" | "USER_POLYGON";
                    source: string;
                }[];
                message: string | null;
                /** @enum {string} */
                status: "AVAILABLE" | "UNAVAILABLE";
            };
            /** Format: uuid */
            id: string;
            latitude: number;
            longitude: number;
            name: string;
            position: {
                accuracyM: number | null;
                description: string;
                label: string;
                note: string;
                source: string;
            };
            updatedAt: string;
            warnings: string[];
        };
        Provenance: {
            ageSeconds?: number;
            confidence?: number;
            dataType: string;
            generatedAt: string;
            location?: components["schemas"]["GeoPoint"];
            modelVersion?: string;
            notes: string[];
            observedAt?: string;
            processingVersion: string;
            provider: string;
            quality?: number;
            source: string;
            /**
             * @description LIVE, UPDATED, FORECAST, ESTIMATED, SIMULATED, DEMO, REFERENCE or UNAVAILABLE.
             * @enum {string}
             */
            status: "LIVE" | "UPDATED" | "FORECAST" | "ESTIMATED" | "SIMULATED" | "DEMO" | "REFERENCE" | "UNAVAILABLE";
            validFor?: string;
        };
        ProvenanceInput: {
            ageSeconds?: number;
            confidence?: number;
            dataType: string;
            generatedAt: string;
            location?: components["schemas"]["GeoPointInput"];
            modelVersion?: string;
            notes: string[];
            observedAt?: string;
            processingVersion: string;
            provider: string;
            quality?: number;
            source: string;
            /**
             * @description LIVE, UPDATED, FORECAST, ESTIMATED, SIMULATED, DEMO, REFERENCE or UNAVAILABLE.
             * @enum {string}
             */
            status: "LIVE" | "UPDATED" | "FORECAST" | "ESTIMATED" | "SIMULATED" | "DEMO" | "REFERENCE" | "UNAVAILABLE";
            validFor?: string;
        };
        SatelliteScene: {
            acquiredAt: string;
            cloudPercent: number | null;
            footprint: {
                coordinates: unknown;
                type: string;
            };
            id: string;
            processedAt: string | null;
            processingStatus: string;
            satellite: string;
            sensor: string;
            source: string;
            thumbnailUrl: string | null;
        };
        SatelliteSceneInput: {
            acquiredAt: string;
            cloudPercent: number | null;
            footprint: {
                coordinates: unknown;
                type: string;
            };
            id: string;
            processedAt: string | null;
            processingStatus: string;
            satellite: string;
            sensor: string;
            source: string;
            thumbnailUrl: string | null;
        };
        User: {
            displayName: string | null;
            email: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "USER" | "ADMIN";
        };
        UserInput: {
            displayName: string | null;
            email: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "USER" | "ADMIN";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
